In [33]:
import math
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n
import pickle

In [10]:
df = pd.read_csv('homeprices2.csv')
df

area  bedrooms  age  prices
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [11]:
#how to deal with missing values
median_bedrooms = math.floor(df['bedrooms'].median())
median_bedrooms

3

In [12]:
#data cleaning
df['bedrooms'] = df['bedrooms'].fillna(median_bedrooms)
df

area  bedrooms  age  prices
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [15]:
df[['area', 'bedrooms', 'age']]

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       3.0   18
3  3600       3.0   30
4  4000       5.0    8

In [17]:
#multiple regression: prices = m1*area + m2*bedrooms + m3*age + b
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df['prices'])

LinearRegression()

In [18]:
#multiple regression: prices = m1*area + m2*bedrooms + m3*age + b
reg.coef_, reg.intercept_
#m1, m2, m3, b

(array([   137.25, -26025.  ,  -6825.  ]), 383724.9999999998)

In [19]:
reg.predict([[3000, 3, 40]]) #predicting a price of home 3000 area, 3 bedrooms, 40 years old

C:\Users\wayla\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [20]:
137.25*3000 + -26025*3 + -6825*40+383725 #checking to see if the equation was inputted correctly

444400.0

In [28]:
#excercise
df2 = pd.read_csv('hiring.csv')
df2['experience'] = df2['experience'].fillna('zero')
df2['experience'] = df2['experience'].apply(w2n.word_to_num) #remember .apply makes the values inputs of the function
df2['test_score(out of 10)'] = df2['test_score(out of 10)'].fillna(df2['test_score(out of 10)'].median())
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [30]:
reg2 = linear_model.LinearRegression()
reg2.fit(df2[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df2['salary($)'])

LinearRegression()

In [32]:
reg2.predict([[9, 5, 7]])

C:\Users\wayla\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([67719.06841339])

In [36]:
#save models for move to different kernels
with open('model_pickle', 'wb') as f:
    pickle.dump(reg2, f)

In [37]:
with open('model_pickle', 'rb') as f: #now a file has the object saved for later use
    mp = pickle.load(f)

In [40]:
mp.predict([[9, 5, 7]])

C:\Users\wayla\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([67719.06841339])